# Generated by Django 5.2.17 on 2026-08-23 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("params", "0001_initial"),
        ("people", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_inicio", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("baja_voluntaria", "Baja voluntaria"),
                            ("liberado", "Lugar liberado"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="activo",
                        max_length=32,
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=255)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regulares",
                        to="people.alumno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regular",
                "verbose_name_plural": "Regulares",
                "ordering": ["-fecha_inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoCobroRegular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anio", models.PositiveSmallIntegerField()),
                ("mes", models.PositiveSmallIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado_a_tiempo", "Pagado a tiempo"),
                            ("pagado_con_recargo", "Pagado con recargo"),
                            ("vencido", "Vencido"),
                            ("liberado", "Lugar liberado"),
                        ],
                        default="pendiente",
                        max_length=32,
                    ),
                ),
                (
                    "alta_parcial",
                    models.BooleanField(
                        default=False,
                        help_text="True si el alta del mes fue después del día 7 (cobro proporcional).",
                    ),
                ),
                (
                    "horas_semana",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "horas_sabado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "horas_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "detalle_calculo",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot: ocurrencias por horario, tarifas usadas, reglas aplicadas.",
                    ),
                ),
                ("calculado_en", models.DateTimeField()),
                (
                    "parametro_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periodos_cobro_regular",
                        to="params.parametroversion",
                    ),
                ),
                (
                    "regular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_cobro",
                        to="regular.regular",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo de cobro Regular",
                "verbose_name_plural": "Periodos de cobro Regular",
                "ordering": ["-anio", "-mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("regular", "anio", "mes"),
                        name="uniq_periodo_cobro_regular_mes",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mes__gte", 1), ("mes__lte", 12)),
                        name="periodo_cobro_regular_mes_valido",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AsignacionRegular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_inicio", models.DateField()),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de liberación lógica del lugar (si aplica).",
                        null=True,
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones_regular",
                        to="scheduling.horario",
                    ),
                ),
                (
                    "regular",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="regular.regular",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Regular",
                "verbose_name_plural": "Asignaciones Regular",
                "ordering": ["horario__dia", "horario__hora_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("activa", True)),
                        fields=("regular", "horario"),
                        name="uniq_asignacion_regular_activa",
                    )
                ],
            },
        ),
    ]
