# Generated by Django 5.2.17 on 2026-09-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_sucursal_salon_sucursal"),
        ("regular", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="regular",
            name="codigo_tarifa",
            field=models.SlugField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="regular",
            name="es_tarifa_fundadora",
            field=models.BooleanField(
                default=False,
                help_text="Del Valle: primeros alumnos ($1440). Si False, tarifa siguiente ($1500).",
            ),
        ),
        migrations.AddField(
            model_name="regular",
            name="plan_horas_semana",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Horas semanales del plan (2 o 3 en Iztacalco).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="regular",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regulares",
                to="catalog.sucursal",
            ),
        ),
        migrations.AlterField(
            model_name="periodocobroregular",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("parcial", "Abono parcial"),
                    ("pagado_a_tiempo", "Pagado a tiempo"),
                    ("pagado_con_recargo", "Pagado con recargo"),
                    ("vencido", "Vencido"),
                    ("liberado", "Lugar liberado"),
                ],
                default="pendiente",
                max_length=32,
            ),
        ),
    ]
