# Generated by Django 5.2.17 on 2026-08-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre_completo", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=32)),
                ("parentesco", models.CharField(blank=True, max_length=64)),
                ("notas", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Tutor",
                "verbose_name_plural": "Tutores",
                "ordering": ["nombre_completo"],
            },
        ),
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre_completo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("adulto", "Adulto"), ("nino", "Niño")], max_length=16
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("pendiente_renovacion", "Pendiente renovación"),
                            ("pago_vencido", "Pago vencido"),
                            ("baja_administrativa", "Baja administrativa"),
                            ("baja_voluntaria", "Baja voluntaria"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="activo",
                        max_length=32,
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=255)),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumnos",
                        to="people.tutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alumno",
                "verbose_name_plural": "Alumnos",
                "ordering": ["nombre_completo"],
            },
        ),
    ]
