# Generated by Django 5.2.17 on 2026-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumno",
            name="telefono",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="alumno",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
