# Generated by Django 5.2.17 on 2026-09-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_sucursal_salon_sucursal"),
        ("people", "0002_alumno_contacto_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="requiere_factura",
            field=models.BooleanField(
                default=False, help_text="Si True, los cobros ofrecen IVA para factura."
            ),
        ),
        migrations.AddField(
            model_name="alumno",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumnos",
                to="catalog.sucursal",
            ),
        ),
    ]
