# Generated by Django 5.2.17 on 2026-08-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("params", "0001_initial"),
        ("people", "0001_initial"),
        ("regular", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EjecucionCobranza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fecha",
                    models.DateField(
                        help_text="Día civil America/Mexico_City procesado.",
                        unique=True,
                    ),
                ),
                ("ejecutado_en", models.DateTimeField()),
                ("detalle", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Ejecución de cobranza",
                "verbose_name_plural": "Ejecuciones de cobranza",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("confirmado", "Confirmado"), ("anulado", "Anulado")],
                        default="confirmado",
                        max_length=16,
                    ),
                ),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fecha_pago",
                    models.DateField(
                        help_text="Fecha civil del pago (America/Mexico_City)."
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=128)),
                ("notas", models.CharField(blank=True, max_length=255)),
                (
                    "reglas_aplicadas",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot del contexto de cobranza al registrar el pago.",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="people.alumno",
                    ),
                ),
                (
                    "metodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="params.metodopagocatalogo",
                    ),
                ),
                (
                    "parametro_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="params.parametroversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha_pago", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LineaCobro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concepto",
                    models.CharField(
                        choices=[
                            ("mensualidad", "Mensualidad"),
                            ("recargo", "Recargo"),
                        ],
                        max_length=32,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada", "Pagada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                (
                    "reglas_aplicadas",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot de tarifas/días/reglas al crear la línea.",
                    ),
                ),
                (
                    "parametro_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas_cobro",
                        to="params.parametroversion",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas_cobro",
                        to="regular.periodocobroregular",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineas",
                        to="billing.pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de cobro",
                "verbose_name_plural": "Líneas de cobro",
                "ordering": ["periodo_id", "concepto"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("periodo", "concepto"),
                        name="uniq_linea_cobro_periodo_concepto",
                    )
                ],
            },
        ),
    ]
