# Generated by Django 5.2.17 on 2026-09-03 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("params", "0001_initial"),
        ("people", "0001_initial"),
        ("regular", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lineacobro",
            name="uniq_linea_cobro_periodo_concepto",
        ),
        migrations.AddField(
            model_name="lineacobro",
            name="alumno",
            field=models.ForeignKey(
                blank=True,
                help_text="Obligatorio para inscripción; en líneas de periodo se deriva del Regular.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lineas_cobro",
                to="people.alumno",
            ),
        ),
        migrations.AlterField(
            model_name="lineacobro",
            name="concepto",
            field=models.CharField(
                choices=[
                    ("mensualidad", "Mensualidad"),
                    ("recargo", "Recargo"),
                    ("inscripcion", "Inscripción"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lineacobro",
            name="periodo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lineas_cobro",
                to="regular.periodocobroregular",
            ),
        ),
        migrations.AddConstraint(
            model_name="lineacobro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("periodo__isnull", False)),
                fields=("periodo", "concepto"),
                name="uniq_linea_cobro_periodo_concepto",
            ),
        ),
        migrations.AddConstraint(
            model_name="lineacobro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("concepto", "inscripcion")),
                fields=("alumno", "concepto"),
                name="uniq_linea_cobro_inscripcion_alumno",
            ),
        ),
    ]
