# Generated by Django 5.2.17 on 2026-09-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_separa_inscripcion_pago"),
        ("params", "0003_parametroversion_horas_aviso_reposicion_and_more"),
        ("people", "0003_alumno_requiere_factura_alumno_sucursal"),
        ("regular", "0002_regular_codigo_tarifa_regular_es_tarifa_fundadora_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoAplicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "verbose_name": "Aplicación de pago",
                "verbose_name_plural": "Aplicaciones de pago",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="lineacobro",
            name="uniq_linea_cobro_periodo_concepto",
        ),
        migrations.RemoveConstraint(
            model_name="lineacobro",
            name="uniq_linea_cobro_inscripcion_alumno",
        ),
        migrations.AddField(
            model_name="lineacobro",
            name="monto_calculado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto de catálogo antes de ajustes operativos.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="monto_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto aplicado a la deuda (sin IVA).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="monto_iva",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="pago",
            name="requiere_factura",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pago",
            name="tasa_iva",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="lineacobro",
            name="concepto",
            field=models.CharField(
                choices=[
                    ("mensualidad", "Mensualidad"),
                    ("recargo", "Recargo"),
                    ("inscripcion", "Inscripción"),
                    ("pack_intro", "Pack intro (4 sesiones)"),
                    ("diferencia_reposicion", "Diferencia reposición"),
                    ("ajuste", "Ajuste / excepción"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lineacobro",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("parcial", "Parcial"),
                    ("pagada", "Pagada"),
                    ("cancelada", "Cancelada"),
                ],
                default="pendiente",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="lineacobro",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("periodo__isnull", False),
                    models.Q(("estado", "cancelada"), _negated=True),
                ),
                fields=("periodo", "concepto"),
                name="uniq_linea_cobro_periodo_concepto",
            ),
        ),
        migrations.AddConstraint(
            model_name="lineacobro",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("concepto", "inscripcion"),
                    models.Q(("estado", "cancelada"), _negated=True),
                ),
                fields=("alumno", "concepto"),
                name="uniq_linea_cobro_inscripcion_alumno",
            ),
        ),
        migrations.AddField(
            model_name="pagoaplicacion",
            name="linea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aplicaciones",
                to="billing.lineacobro",
            ),
        ),
        migrations.AddField(
            model_name="pagoaplicacion",
            name="pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aplicaciones",
                to="billing.pago",
            ),
        ),
    ]
