# Generated by Django 5.2.17 on 2026-08-23 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcepcionAutorizada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("medico_prolongado", "Médico prolongado"),
                            ("otro", "Otro"),
                        ],
                        max_length=32,
                    ),
                ),
                ("motivo", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("solicitada", "Solicitada"),
                            ("autorizada", "Autorizada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="solicitada",
                        max_length=16,
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=255)),
                (
                    "historial",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Eventos append-only (creación, autorización, rechazo).",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="excepciones",
                        to="people.alumno",
                    ),
                ),
                (
                    "autorizador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excepciones_autorizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Excepción autorizada",
                "verbose_name_plural": "Excepciones autorizadas",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
