# Generated by Django 5.2.17 on 2026-08-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("params", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fecha_original",
                    models.DateField(
                        help_text="Fecha de la primera inscripción (inmutable en reglas de negocio)."
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cuota cobrada al alta (snapshot; configurable vía ParametroVersion).",
                        max_digits=10,
                    ),
                ),
                ("pagada", models.BooleanField(default=True)),
                (
                    "alumno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripcion",
                        to="people.alumno",
                    ),
                ),
                (
                    "parametro_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones",
                        to="params.parametroversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción",
                "verbose_name_plural": "Inscripciones",
            },
        ),
    ]
