# Generated by Django 5.2.17 on 2026-09-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscripcion",
            name="pagada",
            field=models.BooleanField(
                default=False,
                help_text="Legacy; la fuente de verdad del pago es billing.LineaCobro.",
            ),
        ),
    ]
