# Generated by Django 5.2.17 on 2026-08-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("params", "0001_initial"),
        ("people", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EjecucionVencimientoFlexi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fecha",
                    models.DateField(
                        help_text="Día civil America/Mexico_City procesado.",
                        unique=True,
                    ),
                ),
                ("ejecutado_en", models.DateTimeField()),
                ("detalle", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Ejecución vencimiento Flexi",
                "verbose_name_plural": "Ejecuciones vencimiento Flexi",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PaqueteFlexi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sesiones_compradas", models.PositiveSmallIntegerField()),
                ("sesiones_disponibles", models.PositiveSmallIntegerField()),
                ("sesiones_consumidas", models.PositiveSmallIntegerField(default=0)),
                ("sesiones_vencidas", models.PositiveSmallIntegerField(default=0)),
                ("meses_vigencia", models.PositiveSmallIntegerField()),
                ("fecha_compra", models.DateField()),
                (
                    "fecha_fin",
                    models.DateField(
                        help_text="Último día de vigencia inclusive (America/Mexico_City)."
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("agotado", "Agotado"),
                            ("vencido", "Vencido"),
                        ],
                        default="activo",
                        max_length=16,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("es_renovacion", models.BooleanField(default=False)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                (
                    "vencido_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Marca de vencimiento (idempotencia del job).",
                        null=True,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paquetes_flexi",
                        to="people.alumno",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paquetes_flexi",
                        to="billing.pago",
                    ),
                ),
                (
                    "parametro_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paquetes_flexi",
                        to="params.parametroversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete Flexi",
                "verbose_name_plural": "Paquetes Flexi",
                "ordering": ["-fecha_compra", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReservaFlexi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_clase", models.DateField()),
                ("hora_inicio", models.TimeField()),
                (
                    "sesiones_usadas",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Horas enteras del horario consumidas como sesiones.",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("reservada", "Reservada"),
                            ("cancelada", "Cancelada (con devolución)"),
                            ("cancelada_tarde", "Cancelada (<24h, consume)"),
                            ("no_show", "No-show (consume)"),
                            ("consumida", "Consumida"),
                        ],
                        default="reservada",
                        max_length=32,
                    ),
                ),
                ("reservada_en", models.DateTimeField()),
                ("cancelada_en", models.DateTimeField(blank=True, null=True)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas_flexi",
                        to="scheduling.horario",
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="flexi.paqueteflexi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva Flexi",
                "verbose_name_plural": "Reservas Flexi",
                "ordering": ["fecha_clase", "hora_inicio", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="paqueteflexi",
            constraint=models.CheckConstraint(
                condition=models.Q(("sesiones_compradas__gte", 1)),
                name="paquete_flexi_sesiones_compradas_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="paqueteflexi",
            constraint=models.CheckConstraint(
                condition=models.Q(("sesiones_disponibles__gte", 0)),
                name="paquete_flexi_sesiones_disponibles_no_neg",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservaflexi",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "reservada")),
                fields=("paquete", "horario", "fecha_clase"),
                name="uniq_reserva_flexi_activa",
            ),
        ),
    ]
