# Generated by Django 5.2.17 on 2026-08-23 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dia",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "duracion_minutos",
                    models.PositiveSmallIntegerField(
                        help_text="Duración de la clase en minutos."
                    ),
                ),
                ("capacidad", models.PositiveSmallIntegerField()),
                (
                    "tipo_alumno",
                    models.CharField(
                        choices=[
                            ("adulto", "Adulto"),
                            ("nino", "Niño"),
                            ("ambos", "Adulto y niño"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "modalidades",
                    models.JSONField(
                        default=list,
                        help_text='Lista de modalidades: "regular", "flexi", "suelta".',
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios",
                        to="catalog.profesor",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios",
                        to="catalog.salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario",
                "verbose_name_plural": "Horarios",
                "ordering": ["dia", "hora_inicio"],
            },
        ),
    ]
