# Generated by Django 5.2.17 on 2026-08-23 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flexi", "0001_initial"),
        ("people", "0001_initial"),
        ("regular", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField()),
                (
                    "modalidad",
                    models.CharField(
                        choices=[("regular", "Regular"), ("flexi", "Flexi")],
                        max_length=16,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("asistio", "Asistió"),
                            ("ausente_alumno", "Ausente (alumno)"),
                            ("cancelada_por_spirit", "Cancelada por Spirit"),
                            ("pendiente_compensacion", "Pendiente compensación"),
                        ],
                        default="programada",
                        max_length=32,
                    ),
                ),
                ("observaciones", models.CharField(blank=True, max_length=255)),
                ("registrado_en", models.DateTimeField(blank=True, null=True)),
                ("detalle", models.JSONField(blank=True, default=dict)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="people.alumno",
                    ),
                ),
                (
                    "asignacion_regular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="regular.asignacionregular",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="scheduling.horario",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asistencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva_flexi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias",
                        to="flexi.reservaflexi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "ordering": ["-fecha", "horario__hora_inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Compensacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reembolso", "Reembolso"),
                            ("reposicion_sin_costo", "Reposición sin costo"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("resuelta", "Resuelta")],
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto de reembolso (si aplica).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("resuelta_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.CharField(blank=True, max_length=255)),
                (
                    "historial",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Eventos append-only (creación, resolución).",
                    ),
                ),
                (
                    "asistencia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compensacion",
                        to="attendance.asistencia",
                    ),
                ),
                (
                    "autorizada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensaciones_autorizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resuelta_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compensaciones_resueltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compensación",
                "verbose_name_plural": "Compensaciones",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="asistencia",
            constraint=models.UniqueConstraint(
                fields=("alumno", "horario", "fecha"),
                name="uniq_asistencia_alumno_horario_fecha",
            ),
        ),
    ]
