# Generated by Django 5.2.17 on 2026-09-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("billing", "0003_pagoaplicacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="es_reposicion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="compensacion",
            name="asistencia_reposicion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compensacion_origen",
                to="attendance.asistencia",
            ),
        ),
        migrations.AddField(
            model_name="compensacion",
            name="linea_cobro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compensaciones",
                to="billing.lineacobro",
            ),
        ),
        migrations.AddField(
            model_name="compensacion",
            name="monto_diferencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cargo por reponer en otra sucursal o duración.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compensacion",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("cancelacion_spirit", "Cancelación por Spirit"),
                    ("aviso_alumno", "Aviso de falta del alumno"),
                ],
                default="cancelacion_spirit",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="compensacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("agendada", "Reposición agendada"),
                    ("resuelta", "Resuelta"),
                ],
                default="pendiente",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="compensacion",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reembolso", "Reembolso"),
                    ("reposicion_sin_costo", "Reposición sin costo"),
                    ("reposicion_con_diferencia", "Reposición con diferencia"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
