# Generated by Django 5.2.17 on 2026-08-23 02:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetodoPagoCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("codigo", models.SlugField(max_length=32, unique=True)),
                ("nombre", models.CharField(max_length=64)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Método de pago",
                "verbose_name_plural": "Métodos de pago",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ParametroVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vigente_desde",
                    models.DateTimeField(
                        help_text="Inicio de vigencia (America/Mexico_City vía USE_TZ)."
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=255)),
                (
                    "tarifa_hora_adulto",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("120.00"), max_digits=10
                    ),
                ),
                (
                    "tarifa_hora_nino",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("110.00"), max_digits=10
                    ),
                ),
                (
                    "precio_clase_suelta",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500.00"), max_digits=10
                    ),
                ),
                (
                    "cuota_inscripcion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500.00"), max_digits=10
                    ),
                ),
                (
                    "monto_recargo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=10
                    ),
                ),
                ("dia_pago_normal_fin", models.PositiveSmallIntegerField(default=7)),
                ("dia_recargo_inicio", models.PositiveSmallIntegerField(default=8)),
                ("dia_recargo_fin", models.PositiveSmallIntegerField(default=10)),
                ("dia_liberacion", models.PositiveSmallIntegerField(default=11)),
                ("flexi_min_sesiones", models.PositiveSmallIntegerField(default=5)),
                ("flexi_max_sesiones", models.PositiveSmallIntegerField(default=30)),
                (
                    "flexi_tarifa_hora",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("120.00"), max_digits=10
                    ),
                ),
                (
                    "flexi_cancelacion_horas",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Horas de anticipación para cancelar sin perder sesión.",
                    ),
                ),
                (
                    "sabado_adulto_sin_descuento_progresivo",
                    models.BooleanField(default=True),
                ),
            ],
            options={
                "verbose_name": "Versión de parámetros",
                "verbose_name_plural": "Versiones de parámetros",
                "ordering": ["-vigente_desde"],
            },
        ),
        migrations.CreateModel(
            name="VigenciaFlexi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sesiones_min", models.PositiveSmallIntegerField()),
                ("sesiones_max", models.PositiveSmallIntegerField()),
                ("meses_vigencia", models.PositiveSmallIntegerField()),
                (
                    "parametro_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vigencias_flexi",
                        to="params.parametroversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vigencia Flexi",
                "verbose_name_plural": "Vigencias Flexi",
                "ordering": ["sesiones_min"],
            },
        ),
        migrations.CreateModel(
            name="BloqueTarifaAdulto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveSmallIntegerField()),
                (
                    "horas_max",
                    models.PositiveSmallIntegerField(
                        help_text="Horas cubiertas por este bloque."
                    ),
                ),
                ("tarifa_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "parametro_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques_adulto",
                        to="params.parametroversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloque tarifa adulto",
                "verbose_name_plural": "Bloques tarifa adulto",
                "ordering": ["orden"],
                "unique_together": {("parametro_version", "orden")},
            },
        ),
    ]
