# Generated by Django 5.2.17 on 2026-09-19 07:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_sucursal_salon_sucursal"),
        ("params", "0002_metodo_pago_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametroversion",
            name="horas_aviso_reposicion",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Horas de anticipación para avisar falta y conservar reposición.",
            ),
        ),
        migrations.AddField(
            model_name="parametroversion",
            name="tasa_iva",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.1600"),
                help_text="IVA a agregar cuando el cliente requiere factura (0.16 = 16%).",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="TarifaSucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        choices=[
                            ("mensual_2h", "Mensualidad 2 horas"),
                            ("mensual_3h", "Mensualidad 3 horas"),
                            ("pack_nuevo_4x3", "Pack nuevo 4 sesiones × 3 h"),
                            ("sesion_3h", "Sesión 3 horas"),
                            ("mensual_fundador", "Mensualidad fundador"),
                            ("mensual_siguiente", "Mensualidad siguiente"),
                        ],
                        max_length=32,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "horas_semana",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("sesiones", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "parametro_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas_sucursal",
                        to="params.parametroversion",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarifas",
                        to="catalog.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa por sucursal",
                "verbose_name_plural": "Tarifas por sucursal",
                "ordering": ["sucursal__nombre", "codigo"],
                "unique_together": {("parametro_version", "sucursal", "codigo")},
            },
        ),
    ]
