# Generated by Django 5.2.17 on 2026-08-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120)),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=64, unique=True)),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Salón",
                "verbose_name_plural": "Salones",
                "ordering": ["nombre"],
            },
        ),
    ]
